# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Import.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setWindowModality(QtCore.Qt.NonModal)
        Dialog.resize(650, 429)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(290, 390, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.ImportDirText = QtWidgets.QPlainTextEdit(Dialog)
        self.ImportDirText.setEnabled(False)
        self.ImportDirText.setGeometry(QtCore.QRect(20, 10, 110, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ImportDirText.sizePolicy().hasHeightForWidth())
        self.ImportDirText.setSizePolicy(sizePolicy)
        self.ImportDirText.setAcceptDrops(False)
        self.ImportDirText.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.ImportDirText.setLineWidth(0)
        self.ImportDirText.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.ImportDirText.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.ImportDirText.setLineWrapMode(QtWidgets.QPlainTextEdit.NoWrap)
        self.ImportDirText.setReadOnly(True)
        self.ImportDirText.setObjectName("ImportDirText")
        self.ImportDir = QtWidgets.QTextEdit(Dialog)
        self.ImportDir.setEnabled(False)
        self.ImportDir.setGeometry(QtCore.QRect(130, 10, 380, 20))
        self.ImportDir.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.ImportDir.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.ImportDir.setObjectName("ImportDir")
        self.ListDirText = QtWidgets.QPlainTextEdit(Dialog)
        self.ListDirText.setEnabled(False)
        self.ListDirText.setGeometry(QtCore.QRect(20, 40, 110, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ListDirText.sizePolicy().hasHeightForWidth())
        self.ListDirText.setSizePolicy(sizePolicy)
        self.ListDirText.setAcceptDrops(False)
        self.ListDirText.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.ListDirText.setLineWidth(0)
        self.ListDirText.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.ListDirText.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.ListDirText.setLineWrapMode(QtWidgets.QPlainTextEdit.NoWrap)
        self.ListDirText.setReadOnly(True)
        self.ListDirText.setObjectName("ListDirText")
        self.WordListPath = QtWidgets.QTextEdit(Dialog)
        self.WordListPath.setGeometry(QtCore.QRect(130, 40, 380, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.WordListPath.sizePolicy().hasHeightForWidth())
        self.WordListPath.setSizePolicy(sizePolicy)
        self.WordListPath.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.WordListPath.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.WordListPath.setObjectName("WordListPath")
        self.browse = QtWidgets.QPushButton(Dialog)
        self.browse.setGeometry(QtCore.QRect(510, 40, 80, 20))
        self.browse.setObjectName("browse")
        self.FrontFormat = QtWidgets.QTextEdit(Dialog)
        self.FrontFormat.setGeometry(QtCore.QRect(20, 130, 300, 251))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.FrontFormat.sizePolicy().hasHeightForWidth())
        self.FrontFormat.setSizePolicy(sizePolicy)
        self.FrontFormat.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.FrontFormat.setObjectName("FrontFormat")
        self.BackFormat = QtWidgets.QTextEdit(Dialog)
        self.BackFormat.setGeometry(QtCore.QRect(330, 130, 300, 250))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BackFormat.sizePolicy().hasHeightForWidth())
        self.BackFormat.setSizePolicy(sizePolicy)
        self.BackFormat.setObjectName("BackFormat")
        self.FrontText = QtWidgets.QPlainTextEdit(Dialog)
        self.FrontText.setEnabled(False)
        self.FrontText.setGeometry(QtCore.QRect(20, 100, 60, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.FrontText.sizePolicy().hasHeightForWidth())
        self.FrontText.setSizePolicy(sizePolicy)
        self.FrontText.setAcceptDrops(False)
        self.FrontText.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.FrontText.setLineWidth(0)
        self.FrontText.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.FrontText.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.FrontText.setLineWrapMode(QtWidgets.QPlainTextEdit.NoWrap)
        self.FrontText.setReadOnly(True)
        self.FrontText.setObjectName("FrontText")
        self.BackText = QtWidgets.QPlainTextEdit(Dialog)
        self.BackText.setEnabled(False)
        self.BackText.setGeometry(QtCore.QRect(330, 100, 60, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BackText.sizePolicy().hasHeightForWidth())
        self.BackText.setSizePolicy(sizePolicy)
        self.BackText.setAcceptDrops(False)
        self.BackText.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.BackText.setLineWidth(0)
        self.BackText.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.BackText.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.BackText.setLineWrapMode(QtWidgets.QPlainTextEdit.NoWrap)
        self.BackText.setReadOnly(True)
        self.BackText.setObjectName("BackText")
        self.DecksNameText = QtWidgets.QPlainTextEdit(Dialog)
        self.DecksNameText.setEnabled(False)
        self.DecksNameText.setGeometry(QtCore.QRect(20, 70, 110, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DecksNameText.sizePolicy().hasHeightForWidth())
        self.DecksNameText.setSizePolicy(sizePolicy)
        self.DecksNameText.setAcceptDrops(False)
        self.DecksNameText.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.DecksNameText.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.DecksNameText.setLineWidth(0)
        self.DecksNameText.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.DecksNameText.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.DecksNameText.setLineWrapMode(QtWidgets.QPlainTextEdit.NoWrap)
        self.DecksNameText.setReadOnly(True)
        self.DecksNameText.setObjectName("DecksNameText")
        self.DecksName = QtWidgets.QTextEdit(Dialog)
        self.DecksName.setGeometry(QtCore.QRect(130, 70, 171, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DecksName.sizePolicy().hasHeightForWidth())
        self.DecksName.setSizePolicy(sizePolicy)
        self.DecksName.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.DecksName.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.DecksName.setObjectName("DecksName")

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Import"))
        self.ImportDirText.setPlainText(_translate("Dialog", "Import directory:"))
        self.ListDirText.setPlainText(_translate("Dialog", "Words List Path:"))
        self.browse.setText(_translate("Dialog", "Browse"))
        self.FrontText.setPlainText(_translate("Dialog", "Front:"))
        self.BackText.setPlainText(_translate("Dialog", "Back:"))
        self.DecksNameText.setPlainText(_translate("Dialog", "Decks Name:"))

